### ISSUE TITLE
Didn't Process Discord Canary and PTB Message Permalink Correctly

### ISSUE THREAD

**Issue by bagusnl** [PoldekPL/SauceBot#1]
When you use for example
`sauce.a https://ptb.discordapp.com/channels/....`
or
`sauce.a https://canary.discordapp.com/channels/....`
It didn't process the image but rather the message itself, so the result will be like this
![image](https://user-images.githubusercontent.com/28079733/94519818-6aab0280-0255-11eb-84d5-432c79f1d137.png)

While the correct one is like this
![image](https://user-images.githubusercontent.com/28079733/94519917-96c68380-0255-11eb-8c43-252a6772b9cc.png)
(Server, channel, and message ID is censored for privacy reason)

Python 3.8.2
Ubuntu Linux 20.04 on WSL2

**Comment by bagusnl** [comment]
Fixed the issue by adding some line of codes after line 296
```            # added function for Discord Canary and PTB
            if re.search(r"https://ptb.discordapp\.com/channels/\d+/\d+/\d+", ctx.message.content, re.I) != None:
                return "discord link"
            if re.search(r"https://canary.discordapp\.com/channels/\d+/\d+/\d+", ctx.message.content, re.I) != None:
                return "discord link"
```

I know it might be not a great solution knowing that I have 0 knowledge in progamming, let alone python, and I just basically strip the existing code and added one word on it. But at least it works.

Edit: Markdown error and added comment

**Comment by PoldekPL** [comment]
Hello, thank you very much for reporting this issue. Sorry for the late reply, but I only found time now to return to this.

I was not even aware of the PTB and Canary Discord environments. I do my development and testing in stable release of Discord, so currently I'm not able to test the changes myself. However, if the messages themselves are not structured differently in them, supporting those links should be very easy - I have changed the link-detecting regex from

```python
https://discordapp\.com/channels/\d+/\d+/\d+
```
to
```python
https://(ptb\.|canary\.){0,1}discordapp\.com/channels/\d+/\d+/\d+
```
and, at least when testing with regex101, it seems to correctly detect both normal and ptb/canary links.

Now, I'll add this change to the repository, but only once I get the bot running again, and for that I'll have to update the bot to run on discord.py 1.5.0 with Intents, so it'll be a few days.

**Comment by PoldekPL** [comment]
The change mentioned above has been added to the repo. If you want to, you can check now if it works in PTB/Canary environments.

**Comment by bagusnl** [comment]
Unfortunately it didn't work and return canary and ptb link as a link and not detect the attachment

**Comment by PoldekPL** [comment]
Okay, I installed Canary and verified the issue. However, I have also immediately noticed my error in the regex. While the example I posted the the first comment is correct, what I added to the code has the optional part in the wrong place. The correction 3d4a283fd1db255aa7dea16dfadf4858c7e5582c has been pushed to the repo and now it seems to work correctly:

![fix](https://user-images.githubusercontent.com/19315380/96439990-a0fdf100-1207-11eb-91ad-04fdb9cadeb7.png)

**Comment by PoldekPL** [comment]
I have done more testing - especially during reimplementing batch mode - and found that, at least in Canary, the domain in the links to messages has changed from `discordapp.com` to `discord.com`. Since the stable release of Discord still returns `discordapp.com`, both possibilities are now handled by the bot.
